"""First-pass analysis helpers."""

from __future__ import annotations

from research_radar.analysis.prompts import triage_prompt
from research_radar.analysis.providers import LLMProvider, Message
from research_radar.models import Artifact, Claim, ClaimStatus, EvidenceAnchor, SourceType


def heuristic_claims(artifacts: list[Artifact]) -> list[Claim]:
    """Create conservative claims without a model for dry runs."""

    claims: list[Claim] = []
    for artifact in artifacts:
        if (
            artifact.source.source_type == SourceType.WEB
            and artifact.content_type == "discovery-summary"
        ):
            continue
        first_line = next((line.strip() for line in artifact.text.splitlines() if line.strip()), "")
        if not first_line:
            continue
        quote = first_line[:500]
        claims.append(
            Claim(
                text=f"{artifact.source.title} is relevant to the monitored topic.",
                status=ClaimStatus.SUPPORTED,
                evidence=[
                    EvidenceAnchor(
                        source_url=artifact.source.url,
                        source_title=artifact.source.title,
                        quote=quote,
                        location="extracted text",
                        confidence=0.75,
                    )
                ],
                rationale="Generated by conservative dry-run heuristic.",
            )
        )
    return claims


def model_triage(artifacts: list[Artifact], provider: LLMProvider, *, model: str) -> str:
    """Run model-based triage and return raw model text."""

    messages = [
        Message(role="system", content="Be precise. Do not invent unsupported facts."),
        Message(role="user", content=triage_prompt(artifacts)),
    ]
    return provider.complete(messages, model=model).content
